// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmNL64L9GetWa2LaBzNtoJgGPjeRu79is',
    appId: '1:209602607942:web:840b4a0b6a9daea4838347',
    messagingSenderId: '209602607942',
    projectId: 'sistema-cadastr-login-flutter',
    authDomain: 'sistema-cadastr-login-flutter.firebaseapp.com',
    storageBucket: 'sistema-cadastr-login-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRHfNPW7M1QuD6HBVAq0kbnMNdr0athQ4',
    appId: '1:209602607942:android:aff9b2d84d592115838347',
    messagingSenderId: '209602607942',
    projectId: 'sistema-cadastr-login-flutter',
    storageBucket: 'sistema-cadastr-login-flutter.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmNL64L9GetWa2LaBzNtoJgGPjeRu79is',
    appId: '1:209602607942:web:c665997d758af712838347',
    messagingSenderId: '209602607942',
    projectId: 'sistema-cadastr-login-flutter',
    authDomain: 'sistema-cadastr-login-flutter.firebaseapp.com',
    storageBucket: 'sistema-cadastr-login-flutter.firebasestorage.app',
  );
}
